apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: reviews-v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI
          value: "mongodb+srv://kanishkadilshan861_db_user:JQryNWrkjeAVeKZn@clustercaregiver.jicvg0d.mongodb.net/caregivers?retryWrites=true&w=majority&appName=Clustercaregiver"
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002