apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiles
  template:
    metadata:
      labels:
        app: profiles
    spec:
      containers:
      - name: profiles
        image: profiles-v1 # Matches the tag from your docker build
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb+srv://kanishkadilshan861_db_user:JQryNWrkjeAVeKZn@clustercaregiver.jicvg0d.mongodb.net/caregivers?retryWrites=true&w=majority&appName=Clustercaregiver" # from /profile's .env file
---
apiVersion: v1
kind: Service
metadata:
  name: profiles-service
spec:
  selector:
    app: profiles
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001