apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
      - name: admin-frontend
        image: admin-v1 # The tag you used for admin frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-service
spec:
  selector:
    app: admin-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80